_wandb:
    value:
        cli_version: 0.21.2
        e:
            dsom3xhc55vj3py8fpapgc7h50unzjhc:
                args:
                    - --vocab
                    - "10000"
                    - --dmod
                    - "512"
                    - --context
                    - "256"
                    - --heads
                    - "16"
                    - --dff
                    - "1344"
                    - --layers
                    - "4"
                    - --theta
                    - "10000"
                    - --lr
                    - "0.001"
                    - --wd
                    - "0.005"
                    - --beta1
                    - "0.9"
                    - --beta2
                    - "0.999"
                    - --eps
                    - "0.00000001"
                    - --device
                    - cuda:0
                    - --dataset
                    - /mnt/c/projects/stanford-cs336/assignment1-basics/.encoded/debmo_test_1-1772905420.npy
                    - --batch
                    - "50"
                    - --steps
                    - "100"
                codePath: cs336_basics/model/train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "47121563648"
                email: yar.d.7772525@gmail.com
                executable: /mnt/c/projects/stanford-cs336/assignment1-basics/.venv/bin/python3
                git:
                    commit: 0e67ec622b4c407491bf5aa4ab28c0348bc8c42b
                    remote: https://github.com/YarO0s/cs336.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-f11ddeeb-190e-6370-a63a-6136dfd7f49d
                host: tuf
                memory:
                    total: "16349519872"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /mnt/c/projects/stanford-cs336/assignment1-basics/cs336_basics/model/train.py
                python: CPython 3.13.12
                root: /mnt/c/projects/stanford-cs336/assignment1-basics/cs336_basics/model
                startedAt: "2026-03-08T05:26:20.003462Z"
                writerId: dsom3xhc55vj3py8fpapgc7h50unzjhc
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 19
            "4": 3.13.12
            "5": 0.21.2
            "12": 0.21.2
            "13": linux-x86_64
learning_rate:
    value: 0.001
